# pytest.ini
[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Coverage configuration
addopts =
    --verbose
    --cov=hypatiax
    --cov-report=html
    --cov-report=term-missing
    --ignore=tests/benchmark

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks integration tests
    benchmark: marks benchmark tests
    functional: mark a test as a functional test.
    unit: marks unit tests

# Test discovery
norecursedirs = .git .tox dist build *.egg
