import numpy as np
import pandas as pd


class FormulaBacktester:
    """
    Test generated formulas on historical data
    """

    def __init__(self, historical_data):
        self.data = historical_data

    def backtest(self, formula_function, params):
        """
        Test formula performance

        Args:
            formula_function: Python function (generated by LLM)
            params: Dictionary of parameter values

        Returns:
            Performance metrics
        """

        results = []

        for i in range(len(self.data)):
            try:
                # Apply formula to each data point
                value = formula_function(**self.data.iloc[i].to_dict())
                results.append(value)
            except Exception as e:
                results.append(None)

        # Calculate performance metrics
        valid_results = [r for r in results if r is not None]

        return {
            "success_rate": len(valid_results) / len(results),
            "mean_value": np.mean(valid_results),
            "std_value": np.std(valid_results),
            "min_value": np.min(valid_results),
            "max_value": np.max(valid_results),
            "failures": len(results) - len(valid_results),
        }
