#!/bin/bash
# Universal environment setup for HypatiaX
# Works in: Local development, GitHub Actions, Docker, Cloud

set -e  # Exit on error

echo "=================================="
echo "HypatiaX Environment Setup"
echo "=================================="
echo ""

# Detect environment
if [ -n "$GITHUB_ACTIONS" ]; then
    ENV_TYPE="github"
    echo "🔷 Environment: GitHub Actions"
elif [ -n "$DOCKER_CONTAINER" ]; then
    ENV_TYPE="docker"
    echo "🐳 Environment: Docker"
elif [ -n "$CI" ]; then
    ENV_TYPE="ci"
    echo "🔄 Environment: CI/CD"
else
    ENV_TYPE="local"
    echo "💻 Environment: Local Development"
fi
echo ""

# Detect project root
if [ -n "$GITHUB_WORKSPACE" ]; then
    # GitHub Actions
    PROJECT_ROOT="$GITHUB_WORKSPACE"
elif [ -n "$HYPATIAX_ROOT" ]; then
    # Already set
    PROJECT_ROOT="$HYPATIAX_ROOT"
else
    # Detect from script location
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    PROJECT_ROOT="$SCRIPT_DIR"
fi

echo "📂 Project Root: $PROJECT_ROOT"

# Validate project structure
if [ ! -d "$PROJECT_ROOT/hypatiax" ]; then
    echo "❌ Error: hypatiax directory not found at $PROJECT_ROOT"
    echo "   Expected structure:"
    echo "   $PROJECT_ROOT/"
    echo "   ├── hypatiax/"
    echo "   ├── tests/"
    echo "   └── setup_environment.sh"
    exit 1
fi

echo "✅ Project structure validated"
echo ""

# ============================================================================
# GITHUB ACTIONS SETUP
# ============================================================================

if [ "$ENV_TYPE" = "github" ]; then
    echo "🔧 Configuring GitHub Actions environment..."

    # Set environment variables for GitHub Actions
    echo "HYPATIAX_ROOT=$PROJECT_ROOT" >> $GITHUB_ENV
    echo "PYTHONPATH=$PROJECT_ROOT:$PYTHONPATH" >> $GITHUB_ENV
    echo "HYPATIAX_OUTPUT_DIR=$PROJECT_ROOT/ci_outputs" >> $GITHUB_ENV

    # Create outputs directory
    mkdir -p "$PROJECT_ROOT/ci_outputs"

    # Set output variables for use in workflow steps
    echo "project_root=$PROJECT_ROOT" >> $GITHUB_OUTPUT
    echo "environment=github" >> $GITHUB_OUTPUT

    echo "✅ GitHub Actions environment configured"
    echo "   Variables added to GITHUB_ENV"
    echo ""

# ============================================================================
# DOCKER SETUP
# ============================================================================

elif [ "$ENV_TYPE" = "docker" ]; then
    echo "🔧 Configuring Docker environment..."

    # Docker environments typically have env vars set in Dockerfile
    # But we can still create runtime config

    export HYPATIAX_ROOT="$PROJECT_ROOT"
    export PYTHONPATH="$PROJECT_ROOT:$PYTHONPATH"
    export HYPATIAX_OUTPUT_DIR="${HYPATIAX_OUTPUT_DIR:-/tmp/hypatiax_outputs}"

    # Create outputs directory
    mkdir -p "$HYPATIAX_OUTPUT_DIR"

    # Write to Docker environment file if it exists
    if [ -w "/etc/environment" ]; then
        echo "HYPATIAX_ROOT=$PROJECT_ROOT" >> /etc/environment
        echo "PYTHONPATH=$PROJECT_ROOT:$PYTHONPATH" >> /etc/environment
    fi

    echo "✅ Docker environment configured"
    echo "   Output directory: $HYPATIAX_OUTPUT_DIR"
    echo ""

# ============================================================================
# LOCAL DEVELOPMENT SETUP
# ============================================================================

else
    echo "🔧 Configuring local development environment..."

    # Create .env file
    ENV_FILE="$PROJECT_ROOT/.env"
    echo "📝 Creating environment file: $ENV_FILE"

    cat > "$ENV_FILE" << EOF
# HypatiaX Environment Configuration
# Auto-generated by setup_environment.sh on $(date)

# Project root directory
export HYPATIAX_ROOT="$PROJECT_ROOT"

# Python path (so you can import hypatiax from anywhere)
export PYTHONPATH="\${HYPATIAX_ROOT}:\${PYTHONPATH}"

# Output directory for generated files
export HYPATIAX_OUTPUT_DIR="\${HYPATIAX_ROOT}/outputs"

# Optional: Add project bin to PATH if you have scripts
export PATH="\${HYPATIAX_ROOT}/bin:\${PATH}"

# Development flags
export HYPATIAX_ENV="local"
EOF

    echo "✅ Environment file created"
    echo ""

    # Create activation script
    ACTIVATE_SCRIPT="$PROJECT_ROOT/activate_hypatiax.sh"
    echo "📝 Creating activation script: $ACTIVATE_SCRIPT"

    cat > "$ACTIVATE_SCRIPT" << 'EOF'
#!/bin/bash
# Source this file to activate HypatiaX environment
# Usage: source activate_hypatiax.sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f "$SCRIPT_DIR/.env" ]; then
    source "$SCRIPT_DIR/.env"
    echo "✅ HypatiaX environment activated"
    echo "   Project Root: $HYPATIAX_ROOT"
    echo "   Python Path:  $PYTHONPATH"
    echo "   Output Dir:   $HYPATIAX_OUTPUT_DIR"
    echo ""
    echo "You can now run scripts from any location!"
    echo ""
    echo "Quick test:"
    echo "  python -c 'from hypatiax.config import config; config.print_config()'"
else
    echo "❌ Error: .env file not found"
    echo "   Run ./setup_environment.sh first"
fi
EOF

    chmod +x "$ACTIVATE_SCRIPT"
    echo "✅ Activation script created"
    echo ""

    # Create outputs directory
    OUTPUTS_DIR="$PROJECT_ROOT/outputs"
    mkdir -p "$OUTPUTS_DIR"
    echo "✅ Outputs directory created: $OUTPUTS_DIR"
    echo ""

    # DON'T overwrite existing config.py - just check it exists
    CONFIG_FILE="$PROJECT_ROOT/hypatiax/config.py"
    if [ -f "$CONFIG_FILE" ]; then
        echo "✅ config.py exists (using existing configuration)"
    else
        echo "⚠️  Warning: config.py not found"
        echo "   Expected at: $CONFIG_FILE"
        echo "   The config module is required for path management"
    fi
    echo ""

    # Update or create .gitignore
    GITIGNORE="$PROJECT_ROOT/.gitignore"

    # Entries to add
    declare -a IGNORE_ENTRIES=(
        "outputs/"
        "ci_outputs/"
        "*.pyc"
        "__pycache__/"
        ".env"
        "*.egg-info/"
        ".pytest_cache/"
        ".coverage"
        "htmlcov/"
    )

    if [ -f "$GITIGNORE" ]; then
        echo "📝 Updating .gitignore..."
        for entry in "${IGNORE_ENTRIES[@]}"; do
            if ! grep -q "^$entry$" "$GITIGNORE" 2>/dev/null; then
                echo "$entry" >> "$GITIGNORE"
            fi
        done
    else
        echo "📝 Creating .gitignore..."
        printf "%s\n" "${IGNORE_ENTRIES[@]}" > "$GITIGNORE"
    fi

    echo "✅ .gitignore configured"
    echo ""
fi

# ============================================================================
# PYTHON ENVIRONMENT VALIDATION
# ============================================================================

echo "🐍 Validating Python environment..."

if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    echo "   ✅ Python3 found: $PYTHON_VERSION"
else
    echo "   ⚠️  Python3 not found in PATH"
fi

# Check if we can import hypatiax
if python3 -c "import sys; sys.path.insert(0, '$PROJECT_ROOT'); import hypatiax" 2>/dev/null; then
    echo "   ✅ hypatiax package is importable"
else
    echo "   ⚠️  hypatiax package cannot be imported"
    echo "      Make sure to set PYTHONPATH or install in development mode"
fi

# Try to validate config
if python3 -c "import sys; sys.path.insert(0, '$PROJECT_ROOT'); from hypatiax.config import config; config.print_config()" 2>/dev/null; then
    echo ""
else
    echo "   ⚠️  config module validation failed"
fi

echo ""

# ============================================================================
# COMPLETION MESSAGE
# ============================================================================

echo "=================================="
echo "✅ Setup Complete!"
echo "=================================="
echo ""

if [ "$ENV_TYPE" = "github" ]; then
    echo "GitHub Actions environment is ready."
    echo "Environment variables have been set in GITHUB_ENV"
    echo ""

elif [ "$ENV_TYPE" = "docker" ]; then
    echo "Docker environment is ready."
    echo "Environment variables are set for this session."
    echo ""

else
    # Local development instructions
    echo "Next steps for local development:"
    echo ""
    echo "1️⃣  Activate the environment:"
    echo "   source activate_hypatiax.sh"
    echo ""
    echo "2️⃣  Or manually set environment variables:"
    echo "   export HYPATIAX_ROOT=\"$PROJECT_ROOT\""
    echo "   export PYTHONPATH=\"$PROJECT_ROOT:\$PYTHONPATH\""
    echo ""
    echo "3️⃣  Run your tests from any directory:"
    echo "   cd /any/directory"
    echo "   python \"$PROJECT_ROOT/tests/test_entity_desc.py\""
    echo "   python \"$PROJECT_ROOT/tests/test_entity_formulas.py\""
    echo ""
    echo "4️⃣  Verify configuration:"
    echo "   python -c 'from hypatiax.config import config; config.print_config()'"
    echo ""
    echo "5️⃣  To make permanent, add to your ~/.bashrc or ~/.zshrc:"
    echo "   echo 'source $ACTIVATE_SCRIPT' >> ~/.bashrc"
    echo ""
    echo "6️⃣  Or install in development mode:"
    echo "   cd \"$PROJECT_ROOT\""
    echo "   pip install -e ."
    echo ""
fi

echo "📚 Documentation: https://docs.hypatiax.io"
echo "🐛 Issues: https://github.com/yourorg/hypatiax/issues"
echo ""
