#!/bin/bash
# Setup environment for HypatiaX project
# Makes it work from any location

set -e  # Exit on error

echo "=================================="
echo "HypatiaX Environment Setup"
echo "=================================="
echo ""

# Detect project root (where this script is located)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR"

echo "📂 Project Root: $PROJECT_ROOT"

# Check if we're in the right place
if [ ! -d "$PROJECT_ROOT/hypatiax" ]; then
    echo "❌ Error: hypatiax directory not found!"
    echo "   Make sure you're running this from the project root"
    exit 1
fi

echo "✅ Project structure validated"
echo ""

# Create .env file
ENV_FILE="$PROJECT_ROOT/.env"
echo "📝 Creating environment file: $ENV_FILE"

cat > "$ENV_FILE" << EOF
# HypatiaX Environment Configuration
# Auto-generated by setup_environment.sh

# Project root directory
export HYPATIAX_ROOT="$PROJECT_ROOT"

# Python path (so you can import hypatiax from anywhere)
export PYTHONPATH="\${HYPATIAX_ROOT}:\${PYTHONPATH}"

# Output directory for generated files
export HYPATIAX_OUTPUT_DIR="\${HYPATIAX_ROOT}/outputs"

# Optional: Add project bin to PATH if you have scripts
export PATH="\${HYPATIAX_ROOT}/bin:\${PATH}"
EOF

echo "✅ Environment file created"
echo ""

# Create activation script
ACTIVATE_SCRIPT="$PROJECT_ROOT/activate_hypatiax.sh"
echo "📝 Creating activation script: $ACTIVATE_SCRIPT"

cat > "$ACTIVATE_SCRIPT" << 'EOF'
#!/bin/bash
# Source this file to activate HypatiaX environment
# Usage: source activate_hypatiax.sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f "$SCRIPT_DIR/.env" ]; then
    source "$SCRIPT_DIR/.env"
    echo "✅ HypatiaX environment activated"
    echo "   Project Root: $HYPATIAX_ROOT"
    echo "   Python Path:  $PYTHONPATH"
    echo ""
    echo "You can now run scripts from any location!"
else
    echo "❌ Error: .env file not found"
    echo "   Run ./setup_environment.sh first"
fi
EOF

chmod +x "$ACTIVATE_SCRIPT"
echo "✅ Activation script created"
echo ""

# Create outputs directory
OUTPUTS_DIR="$PROJECT_ROOT/outputs"
mkdir -p "$OUTPUTS_DIR"
echo "✅ Outputs directory created: $OUTPUTS_DIR"
echo ""

# Create Python configuration module if it doesn't exist
CONFIG_FILE="$PROJECT_ROOT/hypatiax/config.py"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "📝 Creating config.py module..."
    mkdir -p "$(dirname "$CONFIG_FILE")"
    
    cat > "$CONFIG_FILE" << 'PYEOF'
"""Auto-generated configuration for HypatiaX."""
import os
from pathlib import Path

class PathConfig:
    def __init__(self):
        env_root = os.getenv('HYPATIAX_ROOT')
        if env_root:
            self.root = Path(env_root)
        else:
            # Try to find project root
            current = Path(__file__).resolve().parent.parent
            self.root = current
        
        self.hypatiax = self.root / 'hypatiax'
        self.datasets = self.hypatiax / 'datasets'
        self.data_spacy = self.hypatiax / 'data_spacy'
        self.outputs = self.root / 'outputs'
        self.outputs.mkdir(parents=True, exist_ok=True)
    
    def get_output_path(self, *parts):
        path = self.outputs.joinpath(*parts)
        path.parent.mkdir(parents=True, exist_ok=True)
        return path
    
    def print_paths(self):
        print("=" * 70)
        print("HypatiaX Configuration")
        print("=" * 70)
        print(f"Root:     {self.root}")
        print(f"HypatiaX: {self.hypatiax}")
        print(f"Datasets: {self.datasets}")
        print(f"Outputs:  {self.outputs}")
        print("=" * 70)

config = PathConfig()
PYEOF
    
    echo "✅ config.py created"
else
    echo "ℹ️  config.py already exists (skipping)"
fi
echo ""

# Create .gitignore for outputs
GITIGNORE="$PROJECT_ROOT/.gitignore"
if [ ! -f "$GITIGNORE" ]; then
    echo "outputs/" > "$GITIGNORE"
    echo "*.pyc" >> "$GITIGNORE"
    echo "__pycache__/" >> "$GITIGNORE"
    echo ".env" >> "$GITIGNORE"
    echo "✅ .gitignore created"
else
    echo "ℹ️  .gitignore already exists"
fi
echo ""

echo "=================================="
echo "✅ Setup Complete!"
echo "=================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Activate the environment:"
echo "   source activate_hypatiax.sh"
echo ""
echo "2. Or manually set environment variables:"
echo "   export HYPATIAX_ROOT=\"$PROJECT_ROOT\""
echo "   export PYTHONPATH=\"$PROJECT_ROOT:\$PYTHONPATH\""
echo ""
echo "3. Run your tests from any directory:"
echo "   cd /any/directory"
echo "   python $PROJECT_ROOT/tests/test_entity_desc.py"
echo ""
echo "4. To make permanent, add to your ~/.bashrc or ~/.zshrc:"
echo "   echo 'source $ACTIVATE_SCRIPT' >> ~/.bashrc"
echo ""
